DROP TABLE IF EXISTS users;
CREATE TABLE users(INT id PRIMARY KEY, name VARCHAR(255), email VARCHAR(255));

DROP TABLE IF EXISTS categories;
CREATE TABLE categories(INT id PRIMARY KEY, name VARCHAR(255));